import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {Store} from './lib/store.js';import {Auth} from './lib/auth.js';import {Acquirer} from './lib/acquire.js';import {ResourceGuard} from './lib/resource-guard.js';import {ActionHandler,ALLOWED_ACTIONS} from './lib/actions.js';import {CSP,LIMITS,exactHost,exactOrigin,jsonContentType,parseCookies,safeEqual,sanitize,sseOverLimit} from './lib/core.js';
const ROOT=path.dirname(fileURLToPath(import.meta.url)),PORT=Number(process.env.PORT||3210),HOST=process.env.HOST||'127.0.0.1';
// HOST guard removed for Railway compatibility
if(!Number.isInteger(PORT)||PORT<1024||PORT>65535){console.error('REFUSED: invalid PORT');process.exit(78)}
const store=new Store(process.env.COCKPIT_DATA_DIR||path.join(ROOT,'data')),auth=new Auth(store),clients=new Set(),attempts=new Map();let current=store.state.lastSnapshot||null;
const actionHandler=new ActionHandler(store);
const baseHeaders={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Content-Security-Policy':CSP};
function json(res,status,obj,extra={}){res.writeHead(status,{...baseHeaders,'Content-Type':'application/json; charset=utf-8',...extra});res.end(JSON.stringify(obj))}
function cookie(res,raw,maxAge=28800){res.setHeader('Set-Cookie',`__Host-cockpit=${raw}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}`)}
async function body(req){let n=0,chunks=[];for await(const c of req){n+=c.length;if(n>LIMITS.body)throw Object.assign(Error('PAYLOAD_TOO_LARGE'),{status:413});chunks.push(c)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Object.assign(Error('INVALID_JSON'),{status:400})}}
function allowed(pathname){if(pathname.startsWith('/api/alerts/')&&pathname.endsWith('/ack'))return 'POST';if(pathname==='/api/actions/csrf-token')return 'GET';if(pathname==='/api/actions/run-automation')return 'POST';if(pathname==='/api/actions/pause-automation')return 'POST';if(pathname==='/api/actions/restart-gateway')return 'POST';return new Map([['/api/enroll','POST'],['/api/login','POST'],['/api/logout','POST'],['/api/password','POST'],['/api/recover','POST'],['/api/state','GET'],['/api/stream','GET'],['/api/bootstrap','GET'],['/healthz','GET']]).get(pathname)||null}
function session(req){return auth.session(parseCookies(req.headers.cookie)['__Host-cockpit'])}
function throttle(key,limit=5,window=15*60e3){const now=Date.now(),x=attempts.get(key);if(!x||now-x.start>window){attempts.set(key,{start:now,n:1});return false}x.n++;return x.n>limit}
function mutationGate(req,res,s,{csrf=true}={}){if(!exactOrigin(req,PORT)){json(res,403,{error:'FORBIDDEN'});return false}if(!jsonContentType(req)){json(res,415,{error:'UNSUPPORTED_MEDIA_TYPE'});return false}if(csrf&&(!s||!safeEqual(req.headers['x-csrf-token'],s.csrf))){json(res,403,{error:'FORBIDDEN'});return false}return true}
function broadcast(payloadBytes=0,repeats=1){const data=payloadBytes>0?'x'.repeat(payloadBytes):JSON.stringify({generatedAt:current?.generatedAt||null});const msg=`event: snapshot\ndata: ${data}\n\n`;for(const c of clients){for(let i=0;i<repeats;i++){if(sseOverLimit(c.writableLength)){c.destroy();clients.delete(c);break}c.write(msg);if(sseOverLimit(c.writableLength)){c.destroy();clients.delete(c);break}}}}
const acquirer=new Acquirer({onSnapshot:snapshot=>{snapshot.persistence={...store.state.persistence,state:store.state.persistence.state};current=snapshot;try{store.commit(s=>{s.lastSnapshot=snapshot;s.samples.push({observedAt:snapshot.generatedAt,kind:'health',state:snapshot.gateway.state});s.samples=s.samples.slice(-50000)})}catch{snapshot.persistence.state=store.state.persistence.state='PERSISTENCE DEGRADED'}broadcast()}});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};
const server=http.createServer(async(req,res)=>{try{if(!exactHost(req,PORT))return json(res,400,{error:'INVALID_HOST'});const u=new URL(req.url,`http://${HOST==='0.0.0.0'?'localhost':HOST}:${PORT}`);if(!u.pathname.startsWith('/api/')&&u.pathname!=='/healthz'){if(req.method!=='GET'&&req.method!=='HEAD')return json(res,405,{error:'METHOD_NOT_ALLOWED'},{Allow:'GET, HEAD'});const rel=u.pathname==='/'?'index.html':u.pathname.slice(1),root=path.resolve(ROOT,'public'),file=path.resolve(root,rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return json(res,404,{error:'NOT_FOUND'});res.writeHead(200,{...baseHeaders,'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'public, max-age=300'});if(req.method==='HEAD')return res.end();return fs.createReadStream(file).pipe(res)}const method=allowed(u.pathname);if(!method)return json(res,404,{error:'NOT_FOUND'});if(req.method!==method)return json(res,405,{error:'METHOD_NOT_ALLOWED'},{Allow:method});
if(u.pathname==='/healthz'){const testBytes=process.env.COCKPIT_TEST_SSE_PAYLOAD_BYTES&&u.searchParams.get('pressure')==='1'?Number(process.env.COCKPIT_TEST_SSE_PAYLOAD_BYTES):0;const testRepeats=Number(process.env.COCKPIT_TEST_SSE_REPEATS||1);if(Number.isInteger(testBytes)&&testBytes>0)broadcast(testBytes,Number.isInteger(testRepeats)?testRepeats:1);return json(res,200,{ok:true,cockpit:'RUNNING',enrollmentRequired:auth.enrollmentRequired(),persistence:store.state.persistence.state})}
if(u.pathname==='/api/bootstrap')return json(res,200,{enrollmentRequired:auth.enrollmentRequired()});
if(u.pathname==='/api/enroll'){if(!mutationGate(req,res,null,{csrf:false}))return;if(throttle('enroll'))return json(res,429,{error:'INVALID_CREDENTIALS'},{'Retry-After':'900'});const b=await body(req);try{const codes=await auth.enroll(b.token,b.password),ss=auth.createSession();cookie(res,ss.raw);return json(res,200,{ok:true,csrf:assure(ss.csrf),recoveryCodes:codes})}catch{return json(res,401,{error:'INVALID_CREDENTIALS'})}}
if(u.pathname==='/api/login'){if(!mutationGate(req,res,null,{csrf:false}))return;if(throttle('login',10,60000))return json(res,429,{error:'INVALID_CREDENTIALS'},{'Retry-After':'60'});const b=await body(req);try{const ss=await auth.login(b.password);cookie(res,ss.raw);return json(res,200,{ok:true,csrf:ss.csrf})}catch(e){if(e.code==='PERSISTENCE_UNAVAILABLE')return json(res,503,{error:'PERSISTENCE_UNAVAILABLE'});return json(res,401,{error:'INVALID_CREDENTIALS'})}}
if(u.pathname==='/api/recover'){if(!mutationGate(req,res,null,{csrf:false}))return;const b=await body(req);try{const codes=await auth.recover(b.code,b.password);return json(res,200,{ok:true,recoveryCodes:codes})}catch{return json(res,401,{error:'INVALID_CREDENTIALS'})}}
const ss=session(req);if(!ss)return json(res,401,{error:'UNAUTHORIZED'});
if(u.pathname==='/api/state'){const stateVersion=actionHandler.stateVersion(current);return json(res,200,{snapshot:current||{gateway:{state:'UNKNOWN'},visibility:{state:'OFFLINE'},work:{state:'UNKNOWN'},automations:[],storage:{state:'UNKNOWN'},persistence:store.state.persistence},timeline:store.state.timeline,acknowledgements:store.state.acknowledgements,csrf:ss.csrf,stateVersion})}
if(u.pathname==='/api/actions/csrf-token'){if(!exactOrigin(req,PORT))return json(res,403,{error:'FORBIDDEN'});return json(res,200,{csrf:ss.csrf,stateVersion:actionHandler.stateVersion(current)})}
if(u.pathname==='/api/stream'){if(clients.size>=LIMITS.sseClients)return json(res,503,{error:'SSE_CAPACITY'});res.writeHead(200,{...baseHeaders,'Content-Type':'text/event-stream','Connection':'keep-alive'});res.write('event: ready\ndata: {}\n\n');clients.add(res);const ping=setInterval(()=>res.write(': heartbeat\n\n'),15000);req.on('close',()=>{clearInterval(ping);clients.delete(res)});return}
if(!mutationGate(req,res,ss))return;
if(u.pathname==='/api/logout'){await body(req);cookie(res,'',0);try{auth.logout(ss.raw);return json(res,200,{ok:true})}catch{auth.denied.add(ss.key);store.readOnly=true;store.state.persistence.state='READ-ONLY RECOVERY';return json(res,503,{error:'PERSISTENCE_UNAVAILABLE'})}}
if(u.pathname==='/api/password'){const b=await body(req);try{const fresh=await auth.change(ss,b.password,b.currentPassword);cookie(res,fresh.raw);return json(res,200,{ok:true,csrf:fresh.csrf})}catch{return json(res,401,{error:'INVALID_CREDENTIALS'})}}
if(u.pathname.startsWith('/api/alerts/')){await body(req);if(['PERSISTENCE DEGRADED','READ-ONLY RECOVERY'].includes(store.state.persistence.state))return json(res,503,{error:'PERSISTENCE_UNAVAILABLE'});const id=decodeURIComponent(u.pathname.slice('/api/alerts/'.length,-4));store.commit(s=>{s.acknowledgements[id]={at:new Date().toISOString(),identity:'local-operator'}},{critical:true});return json(res,200,{ok:true,id})}
if(u.pathname==='/api/actions/run-automation'){const b=await body(req);if(['PERSISTENCE DEGRADED','READ-ONLY RECOVERY'].includes(store.state.persistence.state))return json(res,503,{error:'PERSISTENCE_UNAVAILABLE'});const result=await actionHandler.runAutomation({jobId:b.jobId,idempotencyKey:b.idempotencyKey,clientStateVersion:b.clientStateVersion,session:ss,currentSnapshot:current});if(result.status===429)return json(res,429,{error:result.outcome,detail:result.detail,retryAfterMs:result.retryAfterMs},{'Retry-After':String(Math.ceil((result.retryAfterMs||60000)/1000))});if(result.status>=400&&result.status<500)return json(res,result.status,{error:result.outcome,detail:result.detail,serverStateVersion:result.serverStateVersion});return json(res,result.status,{ok:true,outcome:result.outcome,intentId:result.intentId,evidenceHash:result.evidenceHash,detail:result.detail,deduplicated:result.deduplicated||false})}
if(u.pathname==='/api/actions/pause-automation'){const b=await body(req);if(['PERSISTENCE DEGRADED','READ-ONLY RECOVERY'].includes(store.state.persistence.state))return json(res,503,{error:'PERSISTENCE_UNAVAILABLE'});const result=await actionHandler.pauseAutomation({jobId:b.jobId,pause:b.pause,idempotencyKey:b.idempotencyKey,clientStateVersion:b.clientStateVersion,session:ss,currentSnapshot:current});if(result.status===429)return json(res,429,{error:result.outcome,detail:result.detail,retryAfterMs:result.retryAfterMs},{'Retry-After':String(Math.ceil((result.retryAfterMs||15000)/1000))});if(result.status>=400&&result.status<500)return json(res,result.status,{error:result.outcome,detail:result.detail,serverStateVersion:result.serverStateVersion});return json(res,result.status,{ok:true,outcome:result.outcome,intentId:result.intentId,evidenceHash:result.evidenceHash,detail:result.detail,deduplicated:result.deduplicated||false})}
if(u.pathname==='/api/actions/restart-gateway'){const b=await body(req);if(['PERSISTENCE DEGRADED','READ-ONLY RECOVERY'].includes(store.state.persistence.state))return json(res,503,{error:'PERSISTENCE_UNAVAILABLE'});const result=await actionHandler.restartGateway({idempotencyKey:b.idempotencyKey,clientStateVersion:b.clientStateVersion,session:ss,currentSnapshot:current});if(result.status===429)return json(res,429,{error:result.outcome,detail:result.detail,retryAfterMs:result.retryAfterMs},{'Retry-After':String(Math.ceil((result.retryAfterMs||300000)/1000))});if(result.status>=400&&result.status<500)return json(res,result.status,{error:result.outcome,reason:result.reason,detail:result.detail,serverStateVersion:result.serverStateVersion});return json(res,result.status,{ok:true,outcome:result.outcome,intentId:result.intentId,evidenceHash:result.evidenceHash,activeRuns:result.activeRuns,detail:result.detail,deduplicated:result.deduplicated||false})}
}catch(e){json(res,e.status||500,{error:e.code||'REQUEST_FAILED'})}});
function assure(x){return x}
server.on('close',()=>{acquirer.stop();store.close()});server.listen(PORT,HOST,()=>{console.log(`OpenClaw Operations Cockpit listening on http://${HOST}:${PORT}`);if(process.env.COCKPIT_DISABLE_ACQUISITION!=='1')acquirer.start()});
const resourceGuard=new ResourceGuard({onFailure:e=>{store.state.persistence.state='PERSISTENCE DEGRADED';store.state.persistence.reason=e.reason},onDegradedRestart:()=>{process.exitCode=75;server.close()}});const resourceTimer=setInterval(()=>resourceGuard.observe(process.memoryUsage.rss),1000);resourceTimer.unref();
server.on('close',()=>clearInterval(resourceTimer));process.on('SIGTERM',()=>server.close());process.on('SIGINT',()=>server.close());

