import {execFile} from 'node:child_process';import {promisify} from 'node:util';import fs from 'node:fs';import path from 'node:path';import {normalizeSnapshot,sanitize,diskState} from './core.js';
import {OutboundBudget} from './outbound.js';
const run=promisify(execFile);
export class Acquirer{
 constructor({intervalMs=15000,deadlineMs=3000,onSnapshot=()=>{},root=process.env.OPENCLAW_HOME||path.join(process.env.USERPROFILE||'','.openclaw'),budget=new OutboundBudget()}={}){this.intervalMs=Math.max(15000,intervalMs);this.deadlineMs=Math.min(3000,deadlineMs);this.onSnapshot=onSnapshot;this.root=path.resolve(root);this.budget=budget;this.timer=null;this.lastCompleteAt=null;this.failures=0;this.running=false}
 async call(method,params){return this.budget.execute(async()=>{const args=['gateway','call',method,'--json'];if(params)args.push('--params',JSON.stringify(params));try{const {stdout}=await run('openclaw',args,{timeout:this.deadlineMs,windowsHide:true,maxBuffer:1024*1024});try{return JSON.parse(stdout)}catch(e){e.kind='schema';throw e}}catch(e){if(e.killed||e.code==='ETIMEDOUT')e.kind='timeout';else if(Number(e.code)>=500)e.status=Number(e.code);else if(e.kind!=='schema')e.kind='transport';throw e}},{key:`gateway:${method}`})}
 async tasks(){let cursor=null,items=[],complete=true,seen=new Set(),started=Date.now();do{if(Date.now()-started>10000){complete=false;break}const p=await this.call('tasks.list',cursor?{cursor}:{limit:100});items.push(...(p.tasks||p.items||p.samples||[]));cursor=p.nextCursor||null;if(cursor&&seen.has(cursor)){complete=false;break}if(cursor)seen.add(cursor)}while(cursor);return {items:sanitize(items),complete}}
 storage(){const root=path.parse(this.root).root||'C:\\';const stat=fs.statfsSync(root,{bigint:true}),freeBytes=Number(stat.bavail*stat.bsize),totalBytes=Number(stat.blocks*stat.bsize),files=[];const bases=[path.join(this.root,'state.sqlite')];for(const p of bases)try{const s=fs.statSync(p);files.push({pathClass:'openclaw-state',extension:path.extname(p),bytes:s.size,lastWriteTimeUtc:s.mtime.toISOString()})}catch{}return {volumeId:root.slice(0,2),freeBytes,totalBytes,observedAt:new Date().toISOString(),files,state:diskState(freeBytes)}}
 async poll(){if(this.running)return;this.running=true;const now=Date.now();try{const [health,status,cron,tasks]=await Promise.all([this.call('health'),this.call('status'),this.call('cron.list'),this.tasks()]);this.lastCompleteAt=new Date().toISOString();this.failures=0;const storage=this.storage();const snapshot=normalizeSnapshot({health:sanitize(health),status:sanitize(status),tasks:tasks.items,tasksComplete:tasks.complete,cron:sanitize(cron),storage,lastCompleteAt:this.lastCompleteAt,persistence:{}},now);snapshot.source={adapterVersion:'1.0.0',authority:'documented structured command',openclawReadOnly:true};this.onSnapshot(snapshot)}catch(e){this.failures++;const snapshot=normalizeSnapshot({lastCompleteAt:this.lastCompleteAt,partial:true,explicitFailures:this.failures,persistence:{}},now);snapshot.acquisitionError={kind:e.killed?'timeout':'unreachable',message:'OpenClaw structured acquisition failed'};this.onSnapshot(snapshot)}finally{this.running=false}}
 start(){this.poll();this.timer=setInterval(()=>this.poll(),this.intervalMs);this.timer.unref()}
 stop(){if(this.timer)clearInterval(this.timer)}
}
