import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {promisify} from 'node:util';import {randomToken,safeEqual,sha} from './core.js';
const scrypt=promisify(crypto.scrypt),PARAMS={N:32768,r:8,p:1,maxmem:64*1024*1024};
async function verifier(secret,salt=crypto.randomBytes(16)){const key=await scrypt(secret,salt,32,PARAMS);return {version:1,algorithm:'scrypt',N:32768,r:8,p:1,maxmem:64*1024*1024,salt:salt.toString('base64'),verifier:Buffer.from(key).toString('base64'),createdAt:new Date().toISOString()}}
async function verify(secret,v){if(!v||v.version!==1||v.algorithm!=='scrypt'||v.N!==32768||v.r!==8||v.p!==1)return false;const x=await verifier(secret,Buffer.from(v.salt,'base64'));return safeEqual(x.verifier,v.verifier)}
export class Auth{
 constructor(store){this.store=store;this.authDir=path.join(store.dir,'auth');this.bootstrapFile=path.join(this.authDir,'bootstrap.token');this.denied=new Set();fs.mkdirSync(this.authDir,{recursive:true,mode:0o700});try{fs.chmodSync(this.authDir,0o700)}catch{};if(!store.state.auth&&!fs.existsSync(this.bootstrapFile)){fs.writeFileSync(this.bootstrapFile,process.env.COCKPIT_BOOTSTRAP_TOKEN||randomToken(32),{mode:0o600,flag:'wx'})}store.secureChildren()}
 enrollmentRequired(){return !this.store.state.auth}
 bootstrapTokenForTest(){return fs.readFileSync(this.bootstrapFile,'utf8')}
 async enroll(token,password){if(!this.enrollmentRequired())throw Error('INVALID_CREDENTIALS');if(!safeEqual(token,fs.readFileSync(this.bootstrapFile,'utf8'))||String(password).length<12)throw Error('INVALID_CREDENTIALS');const codes=Array.from({length:10},()=>randomToken(16)),passwordVerifier=await verifier(password),recovery=[];for(const code of codes)recovery.push({used:false,verifier:await verifier(code)});this.store.commit(s=>{s.auth={password:passwordVerifier,recovery,createdAt:new Date().toISOString()};s.sessions={}}, {critical:true});fs.unlinkSync(this.bootstrapFile);return codes}
 async login(password){if(!this.store.state.auth||!await verify(password,this.store.state.auth.password))throw Error('INVALID_CREDENTIALS');return this.createSession()}
 createSession(){const raw=randomToken(32),csrf=randomToken(32),now=Date.now(),record={csrf,createdAt:now,lastSeenAt:now,idleExpiresAt:now+30*60e3,absoluteExpiresAt:now+8*3600e3};this.store.commit(s=>{s.sessions[sha(raw)]=record},{critical:true});return {raw,csrf,...record}}
 session(raw,{touch=false}={}){if(!raw)return null;const key=sha(raw),s=this.store.state.sessions[key],now=Date.now();if(!s||this.denied.has(key)||now>s.idleExpiresAt||now>s.absoluteExpiresAt)return null;if(touch&&now+60000<s.idleExpiresAt){this.store.commit(x=>{x.sessions[key].lastSeenAt=now;x.sessions[key].idleExpiresAt=Math.min(now+30*60e3,s.absoluteExpiresAt)},{critical:true})}return {...s,key,raw}}
 logout(raw){if(raw)this.denied.add(sha(raw));this.store.commit(s=>{delete s.sessions[sha(raw)]},{critical:true})}
 async change(session,password,current){if(!await verify(current,this.store.state.auth.password)||String(password).length<12)throw Error('INVALID_CREDENTIALS');const next=await verifier(password),freshRaw=randomToken(32),csrf=randomToken(32),now=Date.now();this.store.commit(s=>{s.auth.password=next;s.sessions={[sha(freshRaw)]:{csrf,createdAt:now,lastSeenAt:now,idleExpiresAt:now+30*60e3,absoluteExpiresAt:now+8*3600e3}}},{critical:true});return {raw:freshRaw,csrf}}
 async recover(code,password){if(String(password).length<12)throw Error('INVALID_CREDENTIALS');let index=-1;for(let i=0;i<(this.store.state.auth?.recovery||[]).length;i++)if(!this.store.state.auth.recovery[i].used&&await verify(code,this.store.state.auth.recovery[i].verifier)){index=i;break}if(index<0)throw Error('INVALID_CREDENTIALS');const codes=Array.from({length:10},()=>randomToken(16)),recovery=[];for(const c of codes)recovery.push({used:false,verifier:await verifier(c)});const p=await verifier(password);this.store.commit(s=>{s.auth.password=p;s.auth.recovery[index].used=true;s.auth.recovery=recovery;s.sessions={}},{critical:true});this.denied.clear();return codes}
}
export {verifier,verify,PARAMS};
