import crypto from 'node:crypto';

export const TARGET_VERSION='2026.9.1';
export const GiB=1024**3;
export const LIMITS=Object.freeze({body:256*1024,sseClients:25,ssePressure:128*1024,sseHard:256*1024,db:256*1024**2,wal:64*1024**2,logs:64*1024**2,total:384*1024**2,authReserve:4*1024**2,queueRecords:2000,queueBytes:16*1024**2});
export const CSP="default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'";
export const mutatingRoutes=new Map([['/api/enroll','POST'],['/api/login','POST'],['/api/logout','POST'],['/api/password','POST'],['/api/recover','POST']]);
export function safeEqual(a,b){const x=Buffer.from(String(a??'')),y=Buffer.from(String(b??''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
export function sha(v){return crypto.createHash('sha256').update(v).digest('hex')}
export function randomToken(bytes=32){return crypto.randomBytes(bytes).toString('base64url')}
export function visibility(lastCompleteAt,now=Date.now(),partial=false,explicitFailures=0){if(explicitFailures>=3)return 'OFFLINE';if(!lastCompleteAt)return 'OFFLINE';const age=Math.max(0,now-Date.parse(lastCompleteAt));if(age>90000)return 'OFFLINE';if(partial||age>30000)return 'STALE';return 'LIVE'}
export function runtimeState(v){return v===TARGET_VERSION?'SUPPORTED':'INCOMPATIBLE'}
export function gatewayState(health){if(!health||typeof health.ok!=='boolean')return 'UNKNOWN';if(!health.ok||health.eventLoop?.degraded)return 'DEGRADED';for(const c of health.channels||[])if(c.configured&&(!c.running||!c.connected||c.lastError))return 'DEGRADED';return 'HEALTHY'}
export function diskState(free){if(!Number.isFinite(free)||free<0)return 'UNKNOWN';if(free>=4*GiB)return 'HEALTHY';if(free>=3*GiB)return 'PRESSURE';if(free>=2.5*GiB)return 'PERSISTENCE DEGRADED';return 'READ-ONLY RECOVERY'}
export function diskCurrent(sample,now=Date.now()){return sample&&Number.isFinite(Date.parse(sample.observedAt))&&now-Date.parse(sample.observedAt)<=45000?diskState(sample.freeBytes):'UNKNOWN'}
export function activeWork(status,tasksComplete,tasks,now=Date.now()){const active=status?.tasks?.active,by=status?.tasks?.byStatus;if(!Number.isInteger(active)||active<0||!by||active!==(Number(by.queued||0)+Number(by.running||0)))return {active:null,byStatus:by||{},oldestAgeMs:null,state:'UNKNOWN'};let oldestAgeMs=null;if(tasksComplete){const xs=(tasks||[]).filter(x=>['queued','running'].includes(x.status)).map(x=>Number(x.createdAt)).filter(Number.isFinite);oldestAgeMs=xs.length?now-Math.min(...xs):0}return {active,byStatus:by,oldestAgeMs,state:'KNOWN'}}
export function automationState(job,now=Date.now()){if(!job||!job.id)return {...job,state:'UNKNOWN'};if(job.runningAtMs!=null){const timeout=Number(job.timeoutMs||0),limit=Math.max(timeout*2,30*60*1000);if(now-job.runningAtMs>limit)return {...job,state:'UNKNOWN/STUCK'}}return {...job,state:job.lastRunStatus||'UNKNOWN',deliveryState:job.lastDeliveryStatus||'UNKNOWN'}}
export function growth(samples){if(!Array.isArray(samples)||samples.length<4)return {state:'NOT ENOUGH DATA'};const s=[...samples].sort((a,b)=>a.at-b.at),span=s.at(-1).at-s[0].at;if(span<180000)return {state:'NOT ENOUGH DATA'};for(let i=1;i<s.length;i++)if(s[i].bytes<=s[i-1].bytes)return {state:'NOT ENOUGH DATA'};const bytesPerSecond=(s.at(-1).bytes-s[0].bytes)/(span/1000);return {state:'ESTIMATE',bytesPerSecond}}
export function persistenceState({freeBytes=Infinity,writeFailures=0,checkpointFailures=0,integrity=true}={}){if(!integrity||freeBytes<2.5*GiB)return 'READ-ONLY RECOVERY';if(writeFailures>=2||checkpointFailures>=2||freeBytes<3*GiB)return 'PERSISTENCE DEGRADED';if(freeBytes<4*GiB)return 'PRESSURE';return 'HEALTHY'}
export function normalizeSnapshot({health,status,tasks=[],tasksComplete=false,cron={jobs:[]},storage=null,lastCompleteAt=null,partial=false,explicitFailures=0,persistence={}},now=Date.now()){const vis=visibility(lastCompleteAt,now,partial,explicitFailures),run=runtimeState(status?.runtimeVersion),gateway=vis==='OFFLINE'?'OFFLINE':gatewayState(health),work=activeWork(status,tasksComplete,tasks,now);return {generatedAt:new Date(now).toISOString(),gateway:{state:gateway,version:status?.runtimeVersion||null,runtime:run,evidenceAt:lastCompleteAt,reasons:[...(health?.eventLoop?.reasons||[])]},visibility:{state:vis,lastCompleteAt,ageMs:lastCompleteAt?Math.max(0,now-Date.parse(lastCompleteAt)):null,partial,failures:explicitFailures},work,automations:(cron.jobs||cron.samples||[]).map(j=>automationState(j,now)),storage:storage?{...storage,state:diskCurrent(storage,now)}:{state:'UNKNOWN'},persistence:{...persistence,state:persistence.state||persistenceState(persistence)}}}
export function parseCookies(raw=''){const out={};for(const part of raw.split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=part.slice(i+1).trim()}return out}
export function exactHost(req,port){const raw=req.rawHeaders.filter((x,i)=>i%2===0&&x.toLowerCase()==='host');return raw.length===1&&req.headers.host===`127.0.0.1:${port}`}
export function exactOrigin(req,port){return req.headers.origin===`http://127.0.0.1:${port}`}
export function jsonContentType(req){return /^application\/json(?:;\s*charset=utf-8)?$/i.test(req.headers['content-type']||'')}
export function sseOverLimit(writableLength){return Number(writableLength)>LIMITS.sseHard}
export function sanitize(value){if(value==null||['boolean','number'].includes(typeof value))return value;if(typeof value==='string')return value.slice(0,256).replace(/(?:sk-[\w-]{8,}|Bearer\s+\S+|(?:password|token|cookie|authorization)\s*[=:]\s*\S+)/gi,'[REDACTED]');if(Array.isArray(value))return value.slice(0,200).map(sanitize);if(typeof value==='object'){const o={};for(const [k,v] of Object.entries(value))if(!/prompt|message|content|payload|result|header|cookie|authorization|secret|password|token|memory|path/i.test(k))o[k]=sanitize(v);return o}return null}
