import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {DatabaseSync} from 'node:sqlite';import {LIMITS,sha} from './core.js';import {protectDataDirectory} from './filesystem-security.js';
const EMPTY=()=>({version:1,auth:null,sessions:{},acknowledgements:{},timeline:[],samples:[],persistence:{state:'HEALTHY',writeFailures:0,checkpointFailures:0,integrity:true},lastSnapshot:null});
export class Store{
 constructor(dir,{clock=()=>Date.now()}={}){this.dir=path.resolve(dir);this.file=path.join(this.dir,'cockpit.sqlite');this.wal=`${this.file}-wal`;this.lock=path.join(this.dir,'server.lock');this.clock=clock;this.readOnly=false;this.state=EMPTY();this.prepare();this.open()}
 prepare(){fs.mkdirSync(this.dir,{recursive:true,mode:0o700});try{fs.unlinkSync(this.lock)}catch{};fs.writeFileSync(this.lock,String(process.pid),{flag:'wx',mode:0o600});protectDataDirectory(this.dir)}
 secureChildren(){return protectDataDirectory(this.dir)}
 open(){try{this.db=new DatabaseSync(this.file);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=1000; CREATE TABLE IF NOT EXISTS state (id INTEGER PRIMARY KEY CHECK(id=1), json TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, occurred_at TEXT NOT NULL, kind TEXT NOT NULL, json TEXT NOT NULL);");const integrity=this.db.prepare('PRAGMA integrity_check').get();if(Object.values(integrity)[0]!=='ok')throw Error('integrity check failed');const row=this.db.prepare('SELECT json FROM state WHERE id=1').get();if(row){const x=JSON.parse(row.json);if(x?.version!==1)throw Error('incompatible state');this.state={...EMPTY(),...x};this.state.persistence={...EMPTY().persistence,...x.persistence}}else this.writeState(this.state)}catch(e){if(e?.code==='DATA_DACL_FAILED')throw e;this.readOnly=true;this.state.persistence.state='READ-ONLY RECOVERY';this.state.persistence.integrity=false;this.state.persistence.reason='load_integrity_failure';try{this.db?.close()}catch{};this.db=null}}
 close(){try{this.db?.exec('PRAGMA wal_checkpoint(TRUNCATE)')}catch{}try{this.db?.close()}catch{}try{fs.unlinkSync(this.lock)}catch{}}
 bytes(){const size=f=>{try{return fs.statSync(f).size}catch{return 0}};return {db:size(this.file),wal:size(this.wal),total:size(this.file)+size(this.wal)}}
 writeState(next){const data=JSON.stringify(next),sizes=this.bytes(),worst=Buffer.byteLength(data)+1024*1024;if(sizes.db+worst>LIMITS.db||sizes.wal+worst>LIMITS.wal||sizes.total+worst>LIMITS.total)throw Object.assign(Error('PERSISTENCE_LIMIT'),{code:'PERSISTENCE_LIMIT'});this.db.prepare("INSERT INTO state(id,json,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET json=excluded.json,updated_at=excluded.updated_at").run(data,new Date(this.clock()).toISOString())}
 commit(mutator,{critical=false}={}){if(this.readOnly||!this.db)throw Object.assign(Error('PERSISTENCE_UNAVAILABLE'),{code:'PERSISTENCE_UNAVAILABLE'});const next=structuredClone(this.state);mutator(next);const data=Buffer.byteLength(JSON.stringify(next));if(data>LIMITS.db-(critical?0:LIMITS.authReserve))throw Object.assign(Error('PERSISTENCE_LIMIT'),{code:'PERSISTENCE_LIMIT'});try{this.db.exec('BEGIN IMMEDIATE');this.writeState(next);this.db.exec('COMMIT');this.state=next;this.state.persistence.writeFailures=0;if(this.bytes().wal>=32*1024**2)this.checkpoint();return next}catch(e){try{this.db.exec('ROLLBACK')}catch{}this.state.persistence.writeFailures=(this.state.persistence.writeFailures||0)+1;if(this.state.persistence.writeFailures>=2)this.state.persistence.state='PERSISTENCE DEGRADED';throw e}}
 checkpoint(){try{this.db.exec('PRAGMA wal_checkpoint(TRUNCATE)');this.state.persistence.checkpointFailures=0}catch(e){this.state.persistence.checkpointFailures=(this.state.persistence.checkpointFailures||0)+1;if(this.state.persistence.checkpointFailures>=2)this.state.persistence.state='PERSISTENCE DEGRADED';throw e}}
 addTimeline(event){this.commit(s=>{const clean={id:event.id||crypto.randomUUID(),type:event.type,summary:event.summary,source:event.source||'cockpit',occurredAt:event.occurredAt||new Date(this.clock()).toISOString(),severity:event.severity||'info',evidenceHash:sha(JSON.stringify(event.evidence||{}))};s.timeline.unshift(clean);s.timeline=s.timeline.filter(x=>this.clock()-Date.parse(x.occurredAt)<=30*864e5).slice(0,100000)})}
 prune(){this.commit(s=>{const now=this.clock();s.timeline=s.timeline.filter(x=>now-Date.parse(x.occurredAt)<=30*864e5).slice(0,100000);s.samples=s.samples.filter(x=>now-Date.parse(x.observedAt)<=14*864e5).slice(-50000);for(const [k,v] of Object.entries(s.sessions))if(now>v.absoluteExpiresAt+864e5)delete s.sessions[k]})}
}
